export const GET_LIGHT_STATUS_REQUEST = 'light.GET_LIGHT_STATUS_REQUEST'
export const GET_LIGHT_STATUS_SUCCESS = 'light.GET_LIGHT_STATUS_SUCCESS'
export const GET_LIGHT_STATUS_ERROR = 'light.GET_LIGHT_STATUS_ERROR'
